#ifndef P101_ERROR_PATH_WALK_CONSTANTS_H
#define P101_ERROR_PATH_WALK_CONSTANTS_H

#define FAULT_CALL_ENV "P101_FAULT_CALL"
#define FAULT_ERRNO_ENV "P101_FAULT_ERRNO"
#define FAULT_LOG_ENV "P101_FAULT_LOG"
#define FAULT_NAME_ENV "P101_FAULT_NAME"
#define FAULT_MODE_ENV "P101_FAULT_MODE"
#define FAULT_AMOUNT_ENV "P101_FAULT_AMOUNT"
#define FAULT_REPEAT_ENV "P101_FAULT_REPEAT"
#define RESOURCE_LOG_ENV "P101_RESOURCE_LOG"
#define CALL_LOG_ENV "P101_CALL_LOG"
#define CALL_LOG_ARGS_ENV "P101_CALL_LOG_ARGS"
#define CALL_LOG_RESULT_ENV "P101_CALL_LOG_RESULT"
#define CHILD_FAULT_CALL_ENV "P101_OBSERVE_CHILD_FAULT_CALL"
#define CHILD_FAULT_ERRNO_ENV "P101_OBSERVE_CHILD_FAULT_ERRNO"
#define CHILD_FAULT_LOG_ENV "P101_OBSERVE_CHILD_FAULT_LOG"
#define CHILD_FAULT_NAME_ENV "P101_OBSERVE_CHILD_FAULT_NAME"
#define CHILD_FAULT_MODE_ENV "P101_OBSERVE_CHILD_FAULT_MODE"
#define CHILD_FAULT_AMOUNT_ENV "P101_OBSERVE_CHILD_FAULT_AMOUNT"
#define CHILD_FAULT_REPEAT_ENV "P101_OBSERVE_CHILD_FAULT_REPEAT"
#define DEFAULT_RUN_PATH "p101-run.py"
#define DEFAULT_OBSERVE_PATH "p101-observe"
#define DEFAULT_ANALYZE_PATH "p101-analyze.py"
#define DEFAULT_MODEL_PATH "p101-event-model"
#define RESOURCE_POLICY_SCHEMA "p101-resource-policy-findings-v1"
#define ANALYSIS_POLICY_SCHEMA "p101-analysis-findings-v1"
#define DEFAULT_LOG_PREFIX "/tmp/p101-error-path-walk"

enum
{
    FAULT_LOG_VERSION       = 2,
    MSG_LEN                 = 256,
    FAULT_LEN               = 32,
    READ_BUF_LEN            = 4096,
    POLICY_INITIAL_CAPACITY = 4096,
    POLICY_OUTPUT_LIMIT     = 64 * 1024 * 1024,
    REPORT_FILE_MODE        = 0600,
    EXEC_FAILURE            = 127,
    DEFAULT_MAX_FAILURES    = 1024,
    MAX_FAILURES_LIMIT      = 100000,
    MAX_TOOL_ARGS           = 128,
    EXIT_FINDINGS           = 1,
    EXIT_TROUBLE            = 2
};

#endif    // P101_ERROR_PATH_WALK_CONSTANTS_H
